[profile.default]
src = "contracts"
out = "artifacts"
build_info = true                  # 强制生成 build-info
build_info_path = "artifacts/build-info"  # 明确 build-info 路径
libs = ["node_modules", "lib"]
test = "tests-foundry"
script = "script-foundry"
options = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
