[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
test = "tests-foundry"
script = "script-foundry"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
